app = "mvk-balance-api"
primary_region = "gru"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  FORCE_HTTPS = "false"
  HTTP_ONLY = "true"

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "10s"

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1 